# permissions for end users to view spamapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spamapi-viewer-role
rules:
- apiGroups:
  - cache.spam.com
  resources:
  - spamapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.spam.com
  resources:
  - spamapis/status
  verbs:
  - get
